name: GenoBoost

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --manifest-path ./projects_rust/Cargo.toml --verbose


  #test_example:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: test
  #      run: |
  #        bash ./genoboost.sh

  #test_1kg:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: test
  #      run: |
  #        bash ./genoboost.sh


          
