name: GenoBoost

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
  test_1kg:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          bash ./genoboost.sh
  test_1kg_cv:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: genoboost
          environment-file: ./etc/env.yml
          auto-activate-base: false
          auto-update-conda: true
      - name: test
        run: |
          bash ./genoboost.cv.sh
