# [ref](https://github.com/marketplace/actions/upload-files-to-a-github-release)

name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: genoboost
            asset_name: genoboost-linux-amd64
          #- os: windows-latest
            #artifact_name: mything.exe
            #asset_name: mything-windows-amd64
          #- os: macos-latest
            #artifact_name: mything
            #asset_name: mything-macos-amd64

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: x86_64-unknown-linux-musl
      - name: Build
        run: |
          bash ./create.publish.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.artifact_name }}.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
