# [ref](https://github.com/marketplace/actions/upload-files-to-a-github-release)
# TODO: windows and macos
# https://www.reddit.com/r/rust/comments/5k8uab/crosscompiling_from_ubuntu_to_windows_with_rustup/

name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: genoboost-linux
            asset_name: genoboost-linux.zip
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            artifact_name: genoboost-windows
            asset_name: genoboost-windows.zip
          #- os: windows-latest
          #  target: x86_64-pc-windows-gnu
          #  artifact_name: genoboost-windows
          #  asset_name: genoboost-windows.zip
          #- os: macos-latest
          #  target: x86_64-apple-darwin
          #  artifact_name: genoboost-macos
          #  asset_name: genoboost-macos.zip

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools
          version: 1.0
        # not effective
        #if: contains( ${{ matrix.target }}, 'musl')
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: mingw-w64
          version: 1.0
      - name: Build
        run: |
          bash ./create.publish.sh ${{ matrix.artifact_name }} ${{ matrix.target }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.artifact_name }}.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
